### ISSUE TITLE
Manageproducts.xhtml

### ISSUE THREAD

**Issue by cn222hn** [IHotWoan/TheBestProjectGroup#11]
As you can see the test added product does not get the category specification nor brand specification
![image](https://cloud.githubusercontent.com/assets/18505988/15450815/dcdf4202-1fa7-11e6-9915-1391689d3225.png)

**Comment by songhokun** [comment]
It happens because the select one menu from category and brands only passes ID (integer), but not the name of category or brand in String.

**Comment by songhokun** [comment]
Let me revise addproduct method in supercategory (category bean) class.

**Comment by DyneRidian** [comment]
If you take a look at the productSearch method and use the same query to inner join the tables you can get the names of the categories and brands to be displayed in the productArray datatable.

**Comment by songhokun** [comment]
<img width="1056" alt="screen shot 2016-05-22 at 12 19 34" src="https://cloud.githubusercontent.com/assets/17985422/15453480/0c530ad0-2018-11e6-846e-2fcd074da45e.png">

**Comment by songhokun** [comment]
Fixed the issue. Thank you all for responses.
