### ISSUE TITLE
Punctuation error in supercategory

### ISSUE THREAD

**Issue by DyneRidian** [IHotWoan/TheBestProjectGroup#3]
When a new product is added or edited that has an apostrophe in the description or name, it does not get added to the database. Query is messed up by apostrophe.

**Comment by songhokun** [comment]
Like having apostrophes in java's String reuiqres escpae sequence, we also need to provide  'escape sequence' in front of the quotes in mySQL.

https://dev.mysql.com/doc/refman/5.7/en/string-literals.html

I will add a method iterates over the string in setDescription in product class after having my lunch! :)
