### ISSUE TITLE
Same product is recognised as a different product after filters

### ISSUE THREAD

**Issue by songhokun** [IHotWoan/TheBestProjectGroup#4]
<img width="1145" alt="screen shot 2016-05-09 at 23 42 02" src="https://cloud.githubusercontent.com/assets/17985422/15129118/ef1742d8-163f-11e6-9b86-76a0d1227a90.png">

So, filter seems to call a constructor whenever it is called, and it causes another problem: since it gets new products from the database, (it removes the previous products and fill it with new product classes), same product is recognised as a different class, and results like the picture above.

**Comment by DyneRidian** [comment]
I'm not experiencing this problem Songho, the filters work for me even after a bunch of clicking around filtering through different things, I'm not seeing any duplicates.

**Comment by DyneRidian** [comment]
Hmm, is there a way to do a check to see if the product ID's are matching and if they are then it increases the quantity by 1. I'm looking over your code but its hard for me to follow it so I don't know where to implement this check but hopefully it is as simple as just saying somewhere something like.

for(Product product: productArray){
if(product.getProductID()==newProduct.getProductID()){
// increase product by 1
return;
}
}

productArray.add(newProduct);
