### ISSUE TITLE
Manageuser.xhtml

### ISSUE THREAD

**Issue by cn222hn** [IHotWoan/TheBestProjectGroup#8]
The buttons needs fixing if i press on delete i can not revert back without deleting the user not even if i change page!
![image](https://cloud.githubusercontent.com/assets/18505988/15352660/8614e306-1ce5-11e6-89f0-eb12dfadc258.png)

**Comment by songhokun** [comment]
You mean the cancel button is not working?

**Comment by DyneRidian** [comment]
fixed
